# Generated by Django 6.1 on 2026-08-08 20:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='novidades',
            options={'verbose_name': 'Novidade', 'verbose_name_plural': 'Novidades'},
        ),
        migrations.AlterModelOptions(
            name='trilhas',
            options={'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.RemoveField(
            model_name='parque',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='parque',
            name='dias_aberto',
        ),
        migrations.AddField(
            model_name='parque',
            name='dias_funcionamento',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list),
        ),
        migrations.AddField(
            model_name='parque',
            name='obs_disponibilidade',
            field=models.CharField(blank=True, help_text='Ex: Fechado para manutenção nas segundas-feiras de Janeiro.', max_length=255, null=True),
        ),
    ]
