# Generated by Django 6.1 on 2026-08-08 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0002_alter_eventos_options_alter_novidades_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioFuncionamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(choices=[('segunda-feira', 'Segunda-feira'), ('terça-feira', 'Terça-feira'), ('quarta-feira', 'Quarta-feira'), ('quinta-feira', 'Quinta-feira'), ('sexta-feira', 'Sexta-feira'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], max_length=20)),
                ('horario_abertura', models.TimeField(blank=True, null=True)),
                ('horario_fechamento', models.TimeField(blank=True, null=True)),
                ('fechado', models.BooleanField(default=False)),
                ('observacao_especial', models.CharField(blank=True, help_text='Ex: (Dia dos Pais)', max_length=100, null=True)),
                ('parque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='tereverde.parque')),
            ],
            options={
                'verbose_name': 'Horário de Funcionamento',
                'verbose_name_plural': 'Horários de Funcionamento',
                'unique_together': {('parque', 'dia_semana')},
            },
        ),
    ]
