# Generated by Django 6.1 on 2026-08-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0003_horariofuncionamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='novidades',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='novidades/'),
        ),
    ]
