# Generated by Django 6.1 on 2026-08-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0004_novidades_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilhas',
            name='limite_entrada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trilhas',
            name='limite_saida',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
