# Generated by Django 6.1 on 2026-08-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0005_trilhas_limite_entrada_trilhas_limite_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='novidades',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='parque',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='trilhas',
            name='imagem',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
