# Generated by Django 6.1 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0006_alter_eventos_imagem_alter_novidades_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parque',
            name='StatusOperacao',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('temporada', 'Temporada')], default='aberto', max_length=20),
        ),
    ]
