# Generated by Django 6.1 on 2026-09-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tereverde', '0007_parque_statusoperacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parque',
            old_name='StatusOperacao',
            new_name='statusOperacao',
        ),
        migrations.AddField(
            model_name='trilhas',
            name='statusOperacao',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado'), ('temporada', 'Temporada')], default='temporada', max_length=20),
        ),
    ]
